/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.inpatient.ui.setup;

import com.cv.app.pharmacy.ui.setup.SetupDialog;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author winswe
 */
public class OtherSetup extends javax.swing.JPanel {

  /**
   * Creates new form OtherSetup
   */
  public OtherSetup() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butLDiag = new javax.swing.JButton();
        butDCAutoVouItem = new javax.swing.JButton();

        butLDiag.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butLDiag.setText("Diagnosis");
        butLDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLDiagActionPerformed(evt);
            }
        });

        butDCAutoVouItem.setText("DC Auto Vou Item");
        butDCAutoVouItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDCAutoVouItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butLDiag, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(butDCAutoVouItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butLDiag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDCAutoVouItem)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butLDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLDiagActionPerformed
        // TODO add your handling code here:
        //showDialog("Diagnosis");
        DiagnosisSetup ds = new DiagnosisSetup();
    }//GEN-LAST:event_butLDiagActionPerformed

    private void butDCAutoVouItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDCAutoVouItemActionPerformed
        DCAutoVouItemDialog dialog = new DCAutoVouItemDialog();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butDCAutoVouItemActionPerformed

    private void showDialog(String panelName){
        SetupDialog dialog = new SetupDialog(Util1.getParent(), true, panelName);
        
        //Calculate dialog position to centre.
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screen = toolkit.getScreenSize();
        int x = (screen.width - dialog.getWidth()) /2;
        int y = (screen.height - dialog.getHeight()) /2;
        
        dialog.setLocation(x, y);
        dialog.show();
        System.out.println("After dialog close");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDCAutoVouItem;
    private javax.swing.JButton butLDiag;
    // End of variables declaration//GEN-END:variables
}
