/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.opd.database.entity.FeesTemplate;
import com.cv.app.opd.database.entity.OPDGroup;
import com.cv.app.opd.ui.common.FeesTemplateTableModel;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.Util1;
import java.util.List;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class FeesTemplateSetup extends javax.swing.JDialog {

    static Logger log = Logger.getLogger(FeesTemplateSetup.class.getName());
    private AbstractDataAccess dao;
    private boolean bindStatus = false;
    private FeesTemplateTableModel tableModel = new FeesTemplateTableModel();

    /**
     * Creates new form FeesTemplateSetup
     */
    public FeesTemplateSetup(AbstractDataAccess dao) {
        super(Util1.getParent(), true);
        initComponents();
        this.dao = dao;
        initCombo();
        getTemplate(((OPDGroup) cboGroup.getSelectedItem()).getGroupId());
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void initCombo() {
        try {
            BindingUtil.BindCombo(cboGroup, dao.findAll("OPDGroup"));
            bindStatus = true;
        } catch (Exception ex) {
            log.error("initCombo : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private void getTemplate(int id) {
        try {
            List<FeesTemplate> listFeesTemplate = dao.findAll("FeesTemplate", "groupId = " + id);
            tableModel.setGroupId(id);
            tableModel.setListFeesTemplate(listFeesTemplate);
        } catch (Exception ex) {
            log.error("getTemplate : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private void save() {
        List<FeesTemplate> listFeesTemplate = tableModel.getListFeesTemplate();

        try {
            for (FeesTemplate ft : listFeesTemplate) {
                dao.save(ft);
            }
        } catch (Exception ex) {
            log.error("save : " + ex.getStackTrace()[0].getLineNumber() + " - " + ex.toString());
            dao.rollBack();
        } finally {
            dao.close();
        }
    }

    private void clear() {
        tableModel.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboGroup = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFees = new javax.swing.JTable();
        butClear = new javax.swing.JButton();
        butSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fees Template");

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("OPD Group ");

        cboGroup.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGroupActionPerformed(evt);
            }
        });

        tblFees.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblFees.setModel(tableModel);
        tblFees.setRowHeight(23);
        jScrollPane1.setViewportView(tblFees);

        butClear.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butClear.setText("Clear");
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });

        butSave.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butSave.setText("Save");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboGroup, 0, 157, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butClear)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {butClear, butSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butClear)
                    .addComponent(butSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void cboGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGroupActionPerformed
      if (bindStatus) {
          getTemplate(((OPDGroup) cboGroup.getSelectedItem()).getGroupId());
      }
  }//GEN-LAST:event_cboGroupActionPerformed

  private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
      clear();
  }//GEN-LAST:event_butClearActionPerformed

  private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
      save();
  }//GEN-LAST:event_butSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butClear;
    private javax.swing.JButton butSave;
    private javax.swing.JComboBox cboGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFees;
    // End of variables declaration//GEN-END:variables
}
