/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv.app.opd.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.opd.database.helper.OPDServiceView;
import com.cv.app.opd.ui.common.OPDCategoryCellEditor;
import com.cv.app.opd.ui.common.OPDServiceCategoryChangeTableModel;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import org.apache.log4j.Logger;

/**
 *
 * @author macbook
 */
public class OPDSetupCategoryChange extends javax.swing.JPanel {

    static Logger log = Logger.getLogger(OPDSetupCategoryChange.class.getName());
    private final AbstractDataAccess dao = Global.dao; // Data access object.
    private final OPDServiceCategoryChangeTableModel tableModel = new OPDServiceCategoryChangeTableModel();
    
    /**
     * Creates new form OPDSetupCategoryChange
     */
    public OPDSetupCategoryChange() {
        initComponents();
        chkActive.setSelected(true);
        initTable();
        searchService();
    }

    private void searchService() {
        tableModel.clear();
        
        String strSql = "select group_id, group_name, cat_id, cat_name, service_id, service_name\n"
                + "from v_opd_service where act_status = ?\n"
                + "order by group_name, cat_name, service_name";
        if(chkActive.isSelected()){
            strSql = strSql.replace("?", "true");
        }else{
            strSql = strSql.replace("?", "false");
        }
        
        try{
            ResultSet rs = dao.execSQL(strSql);
            if(rs != null){
                List<OPDServiceView> list = new ArrayList();
                while(rs.next()){
                    OPDServiceView osv = new OPDServiceView(
                            rs.getInt("group_id"),
                            rs.getString("group_name"),
                            rs.getInt("cat_id"),
                            rs.getString("cat_name"),
                            rs.getInt("service_id"),
                            rs.getString("service_name")
                    );
                    
                    list.add(osv);
                }
                
                rs.close();
                tableModel.setList(list);
            }
        }catch(Exception ex){
            log.error("searchService : " + ex.getMessage());
        }finally{
            dao.close();
        }
    }

    private void initTable(){
        tblOPDService.getColumnModel().getColumn(1).setCellEditor(
                    new OPDCategoryCellEditor(dao));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOPDService = new javax.swing.JTable();
        chkActive = new javax.swing.JCheckBox();

        txtSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        tblOPDService.setModel(tableModel);
        tblOPDService.setRowHeight(23);
        jScrollPane1.setViewportView(tblOPDService);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkActive))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOPDService;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
