/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.emr.ui.setup.AgeRangeSetup;
import com.cv.app.ot.ui.setup.AnesthesistTypeSetup;
import com.cv.app.pharmacy.ui.setup.SetupDialog;
import com.cv.app.pharmacy.ui.setup.TownshipSetup;
import com.cv.app.util.Util1;
import com.cv.app.inpatient.ui.setup.DCCustomGroup;
import com.cv.app.ot.ui.setup.OTCustomGroup;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author winswe
 */
public class OtherSetup extends javax.swing.JPanel {

  /**
   * Creates new form OtherSetup
   */
  public OtherSetup() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butCitySetup = new javax.swing.JButton();
        btnPtnOpening = new javax.swing.JButton();
        butAnesthesistType = new javax.swing.JButton();
        butLRAT = new javax.swing.JButton();
        butTechnicianSetup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        butTownshipSetup = new javax.swing.JButton();
        butCustomGroup = new javax.swing.JButton();
        butLabMachineSetup = new javax.swing.JButton();
        butOTCustomGroup = new javax.swing.JButton();
        butDCCustomGroup = new javax.swing.JButton();
        butOTDrDetailId = new javax.swing.JButton();
        butDCDrDetailId = new javax.swing.JButton();

        butCitySetup.setFont(Global.lableFont);
        butCitySetup.setText("City Setup");
        butCitySetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCitySetupActionPerformed(evt);
            }
        });

        btnPtnOpening.setFont(Global.lableFont);
        btnPtnOpening.setText("Patient Opening");
        btnPtnOpening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPtnOpeningActionPerformed(evt);
            }
        });

        butAnesthesistType.setFont(Global.lableFont);
        butAnesthesistType.setText("Anesthesist Type");
        butAnesthesistType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnesthesistTypeActionPerformed(evt);
            }
        });

        butLRAT.setFont(Global.lableFont);
        butLRAT.setText("Lab Result Auto Text");
        butLRAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLRATActionPerformed(evt);
            }
        });

        butTechnicianSetup.setFont(Global.lableFont);
        butTechnicianSetup.setText("Technician Setup");
        butTechnicianSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTechnicianSetupActionPerformed(evt);
            }
        });

        jButton1.setFont(Global.lableFont);
        jButton1.setText("Age Range Setup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        butTownshipSetup.setFont(Global.lableFont);
        butTownshipSetup.setText("Township Setup");
        butTownshipSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTownshipSetupActionPerformed(evt);
            }
        });

        butCustomGroup.setFont(Global.lableFont);
        butCustomGroup.setText("OPD Custom Group");
        butCustomGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCustomGroupActionPerformed(evt);
            }
        });

        butLabMachineSetup.setFont(Global.lableFont);
        butLabMachineSetup.setText("Lab Machine Setup");
        butLabMachineSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLabMachineSetupActionPerformed(evt);
            }
        });

        butOTCustomGroup.setFont(Global.lableFont);
        butOTCustomGroup.setText("OT Custom Group");
        butOTCustomGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOTCustomGroupActionPerformed(evt);
            }
        });

        butDCCustomGroup.setFont(Global.lableFont);
        butDCCustomGroup.setText("DC Custom Group");
        butDCCustomGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDCCustomGroupActionPerformed(evt);
            }
        });

        butOTDrDetailId.setFont(Global.lableFont);
        butOTDrDetailId.setText("OT Dr Detail Id");
        butOTDrDetailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOTDrDetailIdActionPerformed(evt);
            }
        });

        butDCDrDetailId.setFont(Global.lableFont);
        butDCDrDetailId.setText("DC Dr Detail Id");
        butDCDrDetailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDCDrDetailIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butDCCustomGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butOTCustomGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butLRAT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butAnesthesistType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPtnOpening, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butCitySetup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butTechnicianSetup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butTownshipSetup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butCustomGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butLabMachineSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butOTDrDetailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butDCDrDetailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCitySetup)
                    .addComponent(butLabMachineSetup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPtnOpening)
                    .addComponent(butOTDrDetailId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAnesthesistType)
                    .addComponent(butDCDrDetailId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butLRAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butTechnicianSetup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butTownshipSetup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCustomGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butOTCustomGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDCCustomGroup)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void butCitySetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCitySetupActionPerformed
    CitySetup dialog = new CitySetup();
    
    //showDialog("City Setup");
  }//GEN-LAST:event_butCitySetupActionPerformed

    private void btnPtnOpeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPtnOpeningActionPerformed
        // TODO add your handling code here:
        //PatientOpSetup dialog = new PatientOpSetup();
        
        showDialog("Patient Opening Setup");
    }//GEN-LAST:event_btnPtnOpeningActionPerformed

    private void butAnesthesistTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnesthesistTypeActionPerformed
        AnesthesistTypeSetup dialog = new AnesthesistTypeSetup();
        dialog.setVisible(true);
    }//GEN-LAST:event_butAnesthesistTypeActionPerformed

    private void butLRATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLRATActionPerformed
        LabResultAutoCompleteTextSetup dialog = new LabResultAutoCompleteTextSetup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butLRATActionPerformed

    private void butTechnicianSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTechnicianSetupActionPerformed
        TechnicianSetup dialog = new TechnicianSetup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butTechnicianSetupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgeRangeSetup dialog = new AgeRangeSetup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butTownshipSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTownshipSetupActionPerformed
        TownshipSetup dialog = new TownshipSetup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butTownshipSetupActionPerformed

    private void butCustomGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCustomGroupActionPerformed
        OPDCustomGroup dialog = new OPDCustomGroup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butCustomGroupActionPerformed

    private void butLabMachineSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLabMachineSetupActionPerformed
        LabMachineSetup dialog = new LabMachineSetup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butLabMachineSetupActionPerformed

    private void butDCCustomGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDCCustomGroupActionPerformed
        DCCustomGroup dialog = new DCCustomGroup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butDCCustomGroupActionPerformed

    private void butOTCustomGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOTCustomGroupActionPerformed
        OTCustomGroup dialog = new OTCustomGroup();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butOTCustomGroupActionPerformed

    private void butOTDrDetailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOTDrDetailIdActionPerformed
        OTDrDetailIdDialog dialog = new OTDrDetailIdDialog();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butOTDrDetailIdActionPerformed

    private void butDCDrDetailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDCDrDetailIdActionPerformed
        DCDrDetailIdDialog dialog = new DCDrDetailIdDialog();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_butDCDrDetailIdActionPerformed

    private void showDialog(String panelName){
        SetupDialog dialog = new SetupDialog(Util1.getParent(), true, panelName);
        
        //Calculate dialog position to centre.
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screen = toolkit.getScreenSize();
        int x = (screen.width - dialog.getWidth()) /2;
        int y = (screen.height - dialog.getHeight()) /2;
        
        dialog.setLocation(x, y);
        dialog.show();
        System.out.println("After dialog close");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPtnOpening;
    private javax.swing.JButton butAnesthesistType;
    private javax.swing.JButton butCitySetup;
    private javax.swing.JButton butCustomGroup;
    private javax.swing.JButton butDCCustomGroup;
    private javax.swing.JButton butDCDrDetailId;
    private javax.swing.JButton butLRAT;
    private javax.swing.JButton butLabMachineSetup;
    private javax.swing.JButton butOTCustomGroup;
    private javax.swing.JButton butOTDrDetailId;
    private javax.swing.JButton butTechnicianSetup;
    private javax.swing.JButton butTownshipSetup;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
