/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.inpatient.ui.util;

import com.cv.app.common.Global;
import com.cv.app.common.SelectionObserver;
import com.cv.app.common.StartWithRowFilter;
import com.cv.app.opd.database.entity.ClinicPackage;
import com.cv.app.opd.ui.common.ClinicPackageTableModel;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.Util1;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class PackageSearchDialog extends javax.swing.JDialog {

    static Logger log = Logger.getLogger(PackageSearchDialog.class.getName());
    private final ClinicPackageTableModel cpTableModel = new ClinicPackageTableModel();
    private final AbstractDataAccess dao = Global.dao;
    private TableRowSorter<TableModel> sorter;
    private StartWithRowFilter swrf;
    private final SelectionObserver observer;
    private String packageType;

    /**
     * Creates new form PackageSearchDialog
     *
     * @param observer
     */
    public PackageSearchDialog(SelectionObserver observer, String packageType) {
        super(Util1.getParent(), true);
        initComponents();
        this.packageType = packageType;
        initTable();
        this.observer = observer;
    }

    private void initTable() {

        swrf = new StartWithRowFilter(txtFilter);
        sorter = new TableRowSorter(tblPackage.getModel());
        tblPackage.setRowSorter(sorter);

        tblPackage.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPackage.getColumnModel().getColumn(0).setPreferredWidth(300);//Package Name
        tblPackage.getColumnModel().getColumn(1).setPreferredWidth(50);//Price
        tblPackage.getColumnModel().getColumn(2).setPreferredWidth(5);//Status
        try {
            List<ClinicPackage> listCP = null;
            if (packageType.equals("DC")) {
                listCP = dao.findAllHSQL(
                        "select o from ClinicPackage o where o.status = true"
                );
            }else if(packageType.equals("OPD")){
                listCP = dao.findAllHSQL(
                        "select o from ClinicPackage o where o.status = true and o.packageType = 'OPD'"
                );
            }
            cpTableModel.setListCP(listCP);
        } catch (Exception ex) {
            log.error("initTable : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private void select() {
        int selectedRow = tblPackage.getSelectedRow();
        if (selectedRow >= 0) {
            observer.selected("PackageSelect",
                    cpTableModel.getSelectedPackage(tblPackage.convertRowIndexToModel(selectedRow)));
            dispose();
        } else {
            JOptionPane.showMessageDialog(Util1.getParent(), "Please select package.",
                    "No Selection", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPackage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Package Search");
        setPreferredSize(new java.awt.Dimension(1024, 600));

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        tblPackage.setFont(Global.textFont);
        tblPackage.setModel(cpTableModel);
        tblPackage.setRowHeight(23);
        tblPackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPackageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPackage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFilter)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        if (txtFilter.getText().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(swrf);
        }
    }//GEN-LAST:event_txtFilterKeyReleased

    private void tblPackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPackageMouseClicked
        if (evt.getClickCount() == 2) {
            select();
        }
    }//GEN-LAST:event_tblPackageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPackage;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
