/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.util;

import com.cv.app.common.Global;
import com.cv.app.opd.database.entity.Booking;
import com.cv.app.opd.ui.common.AppoimentDrTableModel;
import com.cv.app.util.Util1;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author winswe
 */
public class AppointmentDoctorDialog extends javax.swing.JDialog {

    private final AppoimentDrTableModel model = new AppoimentDrTableModel();
    private int selectedRow = -1;
    private Booking selBK = null;
    /**
     * Creates new form AppointmentDoctorDialog
     */
    public AppointmentDoctorDialog() {
        super(Util1.getParent(), true);
        initComponents();
        initTable();
        actionMapping();
    }

    private void initTable(){
        tblDrList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblDrList.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                selectedRow = tblDrList.getSelectedRow();
            }
        });
    }
    
    public void setData(List<Booking> listBK){
        model.setListBooking(listBK);
    }
    
    public Booking getSelectedBK(){
        selBK = model.getBooking(tblDrList.convertRowIndexToModel(selectedRow));
        return selBK;
    }
    
    private void actionMapping() {
        //Enter event on tblSale
        tblDrList.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "ENTER-Action");
        tblDrList.getActionMap().put("ENTER-Action", actionTblCustomerEnterKey);
    }

    private final Action actionTblCustomerEnterKey = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Appointment Doctor List");

        tblDrList.setFont(Global.textFont);
        tblDrList.setModel(model);
        tblDrList.setRowHeight(23);
        tblDrList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDrListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDrList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDrListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDrListMouseClicked
        if (evt.getClickCount() == 2 && selectedRow >= 0) {
            dispose();
        }
    }//GEN-LAST:event_tblDrListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrList;
    // End of variables declaration//GEN-END:variables
}
