/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.util;

import com.cv.app.common.SelectionObserver;
import com.cv.app.common.StartWithRowFilter;
import com.cv.app.opd.ui.common.AvailableDoctorTableModel;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

/**
 *
 * @author wswe
 */
public class DoctorSearchNameFilterDialog extends javax.swing.JDialog {
    static Logger log = Logger.getLogger(DoctorSearchNameFilterDialog.class.getName());
    private AvailableDoctorTableModel tableModel = new AvailableDoctorTableModel();
    private AbstractDataAccess dao;
    private SelectionObserver observer;
    private int selectedRow = -1;
    private TableRowSorter<TableModel> sorter;
    private final StartWithRowFilter swrfOTGroup;
    private final TableRowSorter<TableModel> sorterOTGroup;
    
    /**
     * Creates new form DoctorSearchDialog
     */
    public DoctorSearchNameFilterDialog(AbstractDataAccess dao, SelectionObserver observer) {
        super(Util1.getParent(), true);
        initComponents();
        this.dao = dao;
        this.observer = observer;
        initCombo();
        initTable();
        search();
        swrfOTGroup = new StartWithRowFilter(txtDoctorName);
        sorterOTGroup = new TableRowSorter(tblDoctor.getModel());
        tblDoctor.setRowSorter(sorterOTGroup);
        
        if (!Util1.getPropValue("system.app.usage.type").equals("Hospital")){
            this.setTitle("Sale Men");
         
        }
        
        Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        setLocation(x, y);
        setVisible(true);
    }

    private void initCombo() {
     
    }
    
    private void initTable() {
        tblDoctor.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblDoctor.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblDoctor.getColumnModel().getColumn(2).setPreferredWidth(50);

        //Define table selection model to single row selection.
        tblDoctor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Adding table row selection listener.
        tblDoctor.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                selectedRow = tblDoctor.getSelectedRow();
            }
        });
    }
    
    private void select() {
        if (selectedRow >= 0) {
            observer.selected("DoctorSearch",
                    tableModel.getDoctor(tblDoctor.convertRowIndexToModel(selectedRow)));
            dispose();
        } else {
            JOptionPane.showMessageDialog(Util1.getParent(), "Please select doctor.",
                    "No Selection", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String getHSQL() {
        String strSql = "select distinct d from Doctor d ";
        String strFilter = null;
    
        if (txtDoctorName.getText() != null && !txtDoctorName.getText().isEmpty()) {
            if (strFilter == null) {
                strFilter = "doctorName like '" + txtDoctorName.getText() + "%'";
            } else {
                strFilter = strFilter + " and doctorName like '" + txtDoctorName.getText() + "%'";
            }
        }

        if (strFilter != null) {
            strSql = strSql + " where " + strFilter + " and d.active = true  order by d.doctorName";
        } else {
            strSql = strSql + " where d.active = true  order by d.doctorName";
        }

        return strSql;
    }

    private void search() {
        String strSql = getHSQL();

        try {
            dao.open();
            tableModel.setListDoctor(dao.findAllHSQL(strSql));
            dao.close();
        } catch (Exception ex) {
            log.error("search : " + ex.getStackTrace()[0].getLineNumber() + " - " + ex.toString());
        }

        lblTotalRec.setText("Total Records : " + tableModel.getRowCount());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDoctorName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        lblTotalRec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor Search");

        txtDoctorName.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });
        txtDoctorName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDoctorNameKeyReleased(evt);
            }
        });

        tblDoctor.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblDoctor.setModel(tableModel);
        tblDoctor.setRowHeight(23);
        tblDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoctor);

        lblTotalRec.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalRec, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDoctorName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRec)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorMouseClicked
        if (evt.getClickCount() == 2 && selectedRow >= 0) {
            select();
        }
    }//GEN-LAST:event_tblDoctorMouseClicked

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtDoctorNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoctorNameKeyReleased
        // TODO add your handling code here:
        if (txtDoctorName.getText().isEmpty()) {
            sorterOTGroup.setRowFilter(null);
        } else {
            if (Util1.getPropValue("system.text.filter.method").equals("SW")) {
                sorterOTGroup.setRowFilter(swrfOTGroup);
            } else {
                sorterOTGroup.setRowFilter(RowFilter.regexFilter(txtDoctorName.getText()));
            }
        }
    }//GEN-LAST:event_txtDoctorNameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalRec;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTextField txtDoctorName;
    // End of variables declaration//GEN-END:variables
}
