/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.util;

import com.cv.app.common.ComBoBoxAutoComplete;
import com.cv.app.common.Global;
import com.cv.app.opd.database.entity.Gender;
import com.cv.app.opd.database.entity.Initial;
import com.cv.app.opd.database.entity.Speciality;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class DoctorSetupFilterDialog extends javax.swing.JDialog {

    static Logger log = Logger.getLogger(DoctorSetupFilterDialog.class.getName());
    private AbstractDataAccess dao;
    private boolean status = false;

    /**
     * Creates new form DoctorSetupFilterDialog
     */
    public DoctorSetupFilterDialog(AbstractDataAccess dao) {
        super(Util1.getParent(), true);
        initComponents();
        this.dao = dao;
        initCombo();

        Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        setLocation(x, y);
        setVisible(true);
    }

    private void initCombo() {
        try {
            BindingUtil.BindComboFilter(cboInitial, dao.findAll("Initial"));
            BindingUtil.BindComboFilter(cboGender, dao.findAll("Gender"));
            BindingUtil.BindComboFilter(cboSpeciality, dao.findAll("Speciality"));

            new ComBoBoxAutoComplete(cboInitial);
            new ComBoBoxAutoComplete(cboGender);
            new ComBoBoxAutoComplete(cboSpeciality);
        } catch (Exception ex) {
            log.error("initCombo : " + ex.getMessage());
        }finally{
            dao.close();
        }
    }

    public boolean getStatus() {
        return status;
    }

    public String getFilter() {
        String strFilter = "";

        if (cboInitial.getSelectedItem() instanceof Initial) {
            Initial initial = (Initial) cboInitial.getSelectedItem();

            if (strFilter.length() > 0) {
                strFilter = strFilter + " and initialID.initialId = "
                        + initial.getInitialId();
            } else {
                strFilter = "initialID.initialId = "
                        + initial.getInitialId();
            }
        }

        if (cboGender.getSelectedItem() instanceof Gender) {
            Gender sex = (Gender) cboGender.getSelectedItem();

            if (strFilter.length() > 0) {
                strFilter = strFilter + " and genderId.genderId = '" + sex.getGenderId() + "'";
            } else {
                strFilter = " genderId.genderId = '" + sex.getGenderId() + "'";
            }
        }

        if (cboSpeciality.getSelectedItem() instanceof Speciality) {
            Speciality speciality = (Speciality) cboSpeciality.getSelectedItem();

            if (strFilter.length() > 0) {
                strFilter = strFilter + " and specId = " + speciality.getSpecId();
            } else {
                strFilter = "specId = " + speciality.getSpecId();
            }
        }

        return strFilter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboInitial = new javax.swing.JComboBox();
        cboGender = new javax.swing.JComboBox();
        cboSpeciality = new javax.swing.JComboBox();
        butfilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor Setup Filter");

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Initial");

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Gender");

        jLabel3.setFont(Global.lableFont);
        jLabel3.setText("Speciality");

        cboInitial.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboInitial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboGender.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboSpeciality.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboSpeciality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        butfilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butfilter.setText("Filter");
        butfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butfilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboInitial, 0, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboSpeciality, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butfilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void butfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butfilterActionPerformed
      status = true;
      dispose();
  }//GEN-LAST:event_butfilterActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butfilter;
    private javax.swing.JComboBox cboGender;
    private javax.swing.JComboBox cboInitial;
    private javax.swing.JComboBox cboSpeciality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
