/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.cv.app.opd.ui.util;

import com.cv.app.opd.database.tempentity.LabUsage;
import com.cv.app.opd.ui.common.LabUsageChoiceTableModel;
import com.cv.app.util.Util1;
import java.util.List;

/**
 *
 * @author winswe
 */
public class LabUsageChoiceDialog extends javax.swing.JDialog {

    private LabUsageChoiceTableModel model = new LabUsageChoiceTableModel();
    /**
     * Creates new form LabUsageChoiceDialog
     */
    public LabUsageChoiceDialog(String vouNo, int serviceId, List<LabUsage> list, int qty) {
        super(Util1.getParent(), true);
        initComponents();
        model.setList(list);
        model.setQty(qty);
        model.setServiceId(serviceId);
        model.setVouNo(vouNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLabTest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMachine = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lab Usage");

        jLabel1.setText("Lab Test : ");

        txtLabTest.setEditable(false);
        txtLabTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabTestActionPerformed(evt);
            }
        });

        jLabel2.setText("Machine : ");

        txtMachine.setEditable(false);

        tblUsage.setModel(model);
        jScrollPane1.setViewportView(tblUsage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLabTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMachine)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLabTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabTestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsage;
    private javax.swing.JTextField txtLabTest;
    private javax.swing.JTextField txtMachine;
    // End of variables declaration//GEN-END:variables
}
