/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.opd.ui.util;

import com.cv.app.common.Global;
import com.cv.app.opd.database.entity.InvestigationResult;
import com.cv.app.opd.database.view.VOpd;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.Util1;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class XRayresultDialog extends javax.swing.JDialog {

    static Logger log = Logger.getLogger(XRayresultDialog.class.getName());
    private InvestigationResult invResult;
    private final AbstractDataAccess dao = Global.dao;

    /**
     * Creates new form XRayresultDialog
     *
     * @param record
     */
    public XRayresultDialog(VOpd record) {
        super(Util1.getParent(), true);
        initComponents();
        getData(record);
    }

    private void getData(VOpd record) {
        try {
            if (record != null) {
                String key = record.getKey().getVouNo() + "-" + record.getKey().getOpdDetailId()
                        + "-" + record.getPatientId() + "-" + record.getKey().getServiceId();
                invResult = (InvestigationResult) dao.find(InvestigationResult.class, key);
                if (invResult != null) {
                    txtXRayResult.setText(invResult.getImpression());
                } else {
                    invResult = new InvestigationResult();
                    invResult.setKeyField(key);
                }
            }
        } catch (Exception ex) {
            log.error("getData : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private void save() {
        if (invResult != null) {
            try {
                invResult.setImpression(txtXRayResult.getText());
                dao.save(invResult);
                this.dispose();
            } catch (Exception ex) {
                log.error("save : " + ex.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtXRayResult = new javax.swing.JTextArea();
        butSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("X-Ray Result");

        txtXRayResult.setColumns(20);
        txtXRayResult.setRows(5);
        jScrollPane1.setViewportView(txtXRayResult);

        butSave.setText("Save");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        save();
    }//GEN-LAST:event_butSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtXRayResult;
    // End of variables declaration//GEN-END:variables
}
