/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.common.ComBoBoxAutoComplete;
import com.cv.app.common.Global;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.CustomerGroup;
import com.cv.app.pharmacy.database.entity.Township;
import com.cv.app.pharmacy.database.entity.TraderType;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.Util1;
import java.awt.Dimension;

/**
 *
 * @author winswe
 */
public class CustomerSetupFilterDialog extends javax.swing.JDialog {

  private AbstractDataAccess dao;
  private boolean status = false;
  
  /**
   * Creates new form CustomerSetupFilterDialog
   */
  public CustomerSetupFilterDialog(AbstractDataAccess dao) {
    super(Util1.getParent(), true);
    initComponents();
    this.dao = dao;
    initCombo();
    
    Dimension screen = Util1.getScreenSize();
    int x = (screen.width - this.getWidth()) / 2;
    int y = (screen.height - this.getHeight()) / 2;
    chkActive.setSelected(true);
    setLocation(x, y);
    setVisible(true);
  }

  private void initCombo() {
    BindingUtil.BindComboFilter(cboCusGroup, dao.findAll("CustomerGroup"));
    BindingUtil.BindComboFilter(cboPriceType, dao.findAll("TraderType"));
    BindingUtil.BindComboFilter(cboTownship, dao.findAll("Township"));
    
    new ComBoBoxAutoComplete(cboCusGroup);
    new ComBoBoxAutoComplete(cboPriceType);
    new ComBoBoxAutoComplete(cboTownship);
  }
  
  public boolean getStatus(){
    return status;
  }
  
  public String getFilter(){
    String strFilter = "";
    
    if(cboCusGroup.getSelectedItem() instanceof CustomerGroup){
      CustomerGroup cusGroup = (CustomerGroup)cboCusGroup.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and traderGroup.groupId = '" 
                + cusGroup.getGroupId() + "'";
      }else{
        strFilter = "traderGroup.groupId = '" 
                + cusGroup.getGroupId() + "'";
      }
    }
    
    if(cboPriceType.getSelectedItem() instanceof TraderType){
      TraderType traderType = (TraderType)cboPriceType.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and typeId.typeId = " + traderType.getTypeId();
      }else{
        strFilter = "typeId.typeId = " + traderType.getTypeId();
      }
    }
    
    if(cboTownship.getSelectedItem() instanceof Township){
      Township township = (Township)cboTownship.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and township.townshipId = " + township.getTownshipId();
      }else{
        strFilter = "township.townshipId = " + township.getTownshipId();
      }
    }
    
    if(strFilter.length() > 0){
      strFilter = strFilter + " and active = " +  chkActive.isSelected();
    }else{
      strFilter = "active = " + chkActive.isSelected();
    }
    
    return strFilter;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCusGroup = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboPriceType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        butFilter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboTownship = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Setup Filter");

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Cus-Group ");

        cboCusGroup.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Price Type ");

        cboPriceType.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        jLabel3.setFont(Global.lableFont);
        jLabel3.setText("Active ");

        butFilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butFilter.setText("Filter");
        butFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFilterActionPerformed(evt);
            }
        });

        jLabel4.setFont(Global.lableFont);
        jLabel4.setText("Township");

        cboTownship.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkActive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(butFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboCusGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboPriceType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTownship, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCusGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboPriceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboTownship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(chkActive, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void butFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFilterActionPerformed
    status = true;
    dispose();
  }//GEN-LAST:event_butFilterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFilter;
    private javax.swing.JComboBox cboCusGroup;
    private javax.swing.JComboBox cboPriceType;
    private javax.swing.JComboBox cboTownship;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
