/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.Customer;
import com.cv.app.pharmacy.database.helper.CusGroupGenStatus;
import com.cv.app.pharmacy.ui.common.CusGroupGenStatusTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import org.springframework.richclient.application.Application;

/**
 *
 * @author winswe
 */
public class GenChildCustomer extends javax.swing.JDialog {
    private final AbstractDataAccess dao;
    private final Customer cus;
    private final CusGroupGenStatusTableModel model;
    /**
     * Creates new form GenChildCustomer
     * @param cus
     * @param dao
     */
    public GenChildCustomer(Customer cus, AbstractDataAccess dao) {
        super(Application.instance().getActiveWindow().getControl(), true);
        initComponents();
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screen = toolkit.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        this.setLocation(x, y);
        this.dao = dao;
        this.cus = cus;
        model = new CusGroupGenStatusTableModel(this.dao, cus.getTraderId());
        tblCusChild.setModel(model);
        model.setListCGGS(getChildData());
        initTable();
        this.show();
    }

    private List<CusGroupGenStatus> getChildData(){
        List<CusGroupGenStatus> listCGGS = new ArrayList();
        String groupId = "-";
        if(cus.getTraderGroup() != null){
            groupId = cus.getTraderGroup().getGroupId();
        }
        String strSql = "select t.trader_id, cg.group_id, cg.group_name, if(ifnull(t.trader_id,'-') = '-', false, true) status " +
            "from customer_group cg left join trader t on cg.group_id = t.group_id and t.parent = '" + cus.getTraderId()
                + "' where cg.group_id <> '" + groupId + "'";
        ResultSet resultSet = dao.execSQL(strSql);
        
        try{
            while (resultSet.next()) {
                CusGroupGenStatus cggs = new CusGroupGenStatus(resultSet.getString("group_id"),
                    resultSet.getString("group_name"), resultSet.getBoolean("status"),
                    resultSet.getString("trader_id"));

                listCGGS.add(cggs);
            }
        }catch(Exception ex){
            
        }finally{
            try{
                resultSet.close();
            }catch(Exception ex){}
        }
        
        return listCGGS;
    }
    
    private void initTable(){
        tblCusChild.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblCusChild.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblCusChild.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCusChild = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCusChild.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblCusChild.setRowHeight(23);
        jScrollPane1.setViewportView(tblCusChild);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCusChild;
    // End of variables declaration//GEN-END:variables
}
