/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.common.ComBoBoxAutoComplete;
import com.cv.app.common.Global;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.Category;
import com.cv.app.pharmacy.database.entity.ItemBrand;
import com.cv.app.pharmacy.database.entity.ItemType;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.Util1;
import java.awt.Dimension;

/**
 *
 * @author winswe
 */
public class ItemSetupFilterDialog extends javax.swing.JDialog {

  private AbstractDataAccess dao;
  private boolean status = false;

  /**
   * Creates new form ItemSetupFilterDialog
   */
  public ItemSetupFilterDialog(AbstractDataAccess dao) {
    super(Util1.getParent(), true);
    initComponents();
    this.dao = dao;
    initCombo();

    Dimension screen = Util1.getScreenSize();
    int x = (screen.width - this.getWidth()) / 2;
    int y = (screen.height - this.getHeight()) / 2;

    setLocation(x, y);
    setVisible(true);
  }

  private void initCombo() {
    BindingUtil.BindComboFilter(cboBrandName, dao.findAll("ItemBrand"));
    BindingUtil.BindComboFilter(cboCategory, dao.findAll("Category"));
    BindingUtil.BindComboFilter(cboItemType, dao.findAll("ItemType"));

    new ComBoBoxAutoComplete(cboBrandName);
    new ComBoBoxAutoComplete(cboCategory);
    new ComBoBoxAutoComplete(cboItemType);
  }

  public boolean getStatus(){
    return status;
  }
  
  public String getFilter(){
    String strFilter = "";
    
    if(cboItemType.getSelectedItem() instanceof ItemType){
      ItemType itemType = (ItemType)cboItemType.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and medTypeId = '" 
                + itemType.getItemTypeCode() + "'";
      }else{
        strFilter = "medTypeId = '" 
                + itemType.getItemTypeCode() + "'";
      }
    }
    
    if(cboCategory.getSelectedItem() instanceof Category){
      Category cat = (Category)cboCategory.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and catId = " + cat.getCatId();
      }else{
        strFilter = " catId = " + cat.getCatId();
      }
    }
    
    if(cboBrandName.getSelectedItem() instanceof ItemBrand){
      ItemBrand itemBrand = (ItemBrand)cboBrandName.getSelectedItem();
      
      if(strFilter.length() > 0){
        strFilter = strFilter + " and brandId = " + itemBrand.getBrandId();
      }else{
        strFilter = "brandId = " + itemBrand.getBrandId();
      }
    }
    
    /*if(!txtChemicalName.getText().isEmpty()){
      if(strFilter.length() > 0){
        strFilter = strFilter + " and chemicalName like '" 
                + txtChemicalName.getText() + "%'";
      }else{
        strFilter = "chemicalName like '" 
                + txtChemicalName.getText() + "%'";
      }
    }*/
    
    if(strFilter.length() > 0){
      strFilter = strFilter + " and active = " +  chkActive.isSelected();
    }else{
      strFilter = "active = " + chkActive.isSelected();
    }
    
    return strFilter;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboItemType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboCategory = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboBrandName = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtChemicalName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        butFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Filter");

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Item Type ");

        cboItemType.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboItemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Category ");

        cboCategory.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(Global.lableFont);
        jLabel3.setText("Brand Name");

        cboBrandName.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        cboBrandName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(Global.lableFont);
        jLabel4.setText("Chemical Name");

        txtChemicalName.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        jLabel5.setFont(Global.lableFont);
        jLabel5.setText("Active ");

        butFilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        butFilter.setText("Filter");
        butFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboItemType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkActive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(butFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtChemicalName)
                            .addComponent(cboBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboItemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChemicalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(chkActive))
                    .addComponent(butFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void butFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFilterActionPerformed
    status = true;
    dispose();
  }//GEN-LAST:event_butFilterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFilter;
    private javax.swing.JComboBox cboBrandName;
    private javax.swing.JComboBox cboCategory;
    private javax.swing.JComboBox cboItemType;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtChemicalName;
    // End of variables declaration//GEN-END:variables
}
