/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.common.SelectionObserver;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.ui.common.PaymentListTableModel;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.log4j.Logger;

/**
 *
 * @author WSwe
 */
public class PaymentListDialog extends javax.swing.JDialog {
    //static Logger log = Logger.getLogger(PaymentListDialog.class.getName());
    private SelectionObserver observer;
    private String traderId;
    private int selectedRow = -1;
    private AbstractDataAccess dao;
    private PaymentListTableModel tableModel = new PaymentListTableModel();
    
    /**
     * Creates new form PaymentListDialog
     */
    public PaymentListDialog(AbstractDataAccess dao, SelectionObserver selection,
            String traderId) {
        super(Util1.getParent(), true);
        initComponents();
        
        this.dao = dao;
        this.observer = selection;
        this.traderId = traderId;
        
        getPayment();
        initTable();
        
        Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) /2;
        int y = (screen.height - this.getHeight()) /2;

        setLocation(x, y);
        setVisible(true);
    }

    private void initTable() {
        tblPayList.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblPayList.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblPayList.getColumnModel().getColumn(2).setPreferredWidth(50);

        tblPayList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPayList.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
                  @Override
                    public void valueChanged(ListSelectionEvent e) {
                        selectedRow = tblPayList.getSelectedRow();
                    }
                });
    }

    private void getPayment(){
        tableModel.setListTraderPayHis(dao.findAllHSQL(getHSQL()));
    }
    
    private String getHSQL(){
        String strSql = "select v from TraderPayHis v where v.trader.traderId = '"
                + traderId + "' and v.deleted = false and v.saleVou is null and v.paidAmtC <> 0";
        
        return strSql;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment List");

        tblPayList.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblPayList.setModel(tableModel);
        tblPayList.setRowHeight(23);
        tblPayList.setShowVerticalLines(false);
        tblPayList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPayListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPayList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPayListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPayListMouseClicked
        if(evt.getClickCount() == 2 && selectedRow >= 0){
            observer.selected("SelectPayment", 
                    tableModel.getPayment(tblPayList.convertRowIndexToModel(selectedRow)));
            
            //dispose();
        }
    }//GEN-LAST:event_tblPayListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayList;
    // End of variables declaration//GEN-END:variables
}
