/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.ui.entry.PriceChange1;
import com.cv.app.util.Util1;
import java.awt.Container;

/**
 *
 * @author WSwe
 */
public class PriceChangeDialog extends javax.swing.JDialog {

    /**
     * Creates new form PriceChangeDialog
     */
    public PriceChangeDialog() {
        super(Util1.getParent(), true);
        initComponents();
        
        /*Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        setLocation(x, y);
        setVisible(true);*/
    }

    public void addPanel(String selectedMedId){
        Container contentPane = getContentPane();
        contentPane.add(new PriceChange1(selectedMedId));
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Price Change");
        setPreferredSize(new java.awt.Dimension(1366, 800));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
