/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.database.entity.PurDetailHis;
import com.cv.app.pharmacy.database.entity.PurchaseOutstand;
import com.cv.app.pharmacy.ui.common.PurchaseOutstandTableModel;
import com.cv.app.pharmacy.util.MedicineUP;
import com.cv.app.ui.common.BestTableCellEditor;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JLabel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author WSwe
 */
public class PurchaseOutstandingDialog extends javax.swing.JDialog {
    private PurchaseOutstandTableModel tableModel;
    
    /**
     * Creates new form SaleOutstandingDialog
     */
    public PurchaseOutstandingDialog(List<PurDetailHis> listPurDetail, 
            MedicineUP medUp, List<PurchaseOutstand> listPurOutstand) {
        super(Util1.getParent(), true);
        initComponents();
        
        tableModel = new PurchaseOutstandTableModel(listPurDetail, medUp);
        tableModel.setListPurOutstand(listPurOutstand);
        tblPurOutstand.setModel(tableModel);
        initTable();
        actionMapping();
        
        Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        setLocation(x, y);
        this.setVisible(true);
    }

    private void initTable(){
        //Adjust column width
        tblPurOutstand.getColumnModel().getColumn(0).setPreferredWidth(50);//Option
        tblPurOutstand.getColumnModel().getColumn(1).setPreferredWidth(50);//Code
        tblPurOutstand.getColumnModel().getColumn(2).setPreferredWidth(200);//Description
        tblPurOutstand.getColumnModel().getColumn(3).setPreferredWidth(60);//Exp-Date
        tblPurOutstand.getColumnModel().getColumn(4).setPreferredWidth(60);//Outs-Qty
        
        tblPurOutstand.getColumnModel().getColumn(4).setCellEditor(new BestTableCellEditor());
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblPurOutstand.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
    }
    
    public List<PurchaseOutstand> getOutsList(){
        return tableModel.getListPurOutstand();
    }
    
    private void actionMapping(){
        tblPurOutstand.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        tblPurOutstand.getActionMap().put("ESCAPE", actionClose);
    }
    
    private Action actionClose = new AbstractAction(){
        @Override
        public void actionPerformed(ActionEvent e){ 
            dispose();
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurOutstand = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Outstanding Entry");

        tblPurOutstand.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblPurOutstand.setRowHeight(23);
        jScrollPane1.setViewportView(tblPurOutstand);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurOutstand;
    // End of variables declaration//GEN-END:variables
}
