/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.database.entity.PurDetailHis;
import com.cv.app.pharmacy.database.entity.PurchaseIMEINo;
import com.cv.app.pharmacy.ui.common.PurchaseIMEIDetailTableModel;
import com.cv.app.pharmacy.ui.common.PurchaseIMEITableModel;
import com.cv.app.util.Util1;
import java.util.List;

/**
 *
 * @author winswe
 */
public class PurchaseIMEIEntryDialog extends javax.swing.JDialog {
    
    private List<PurchaseIMEINo> listIMEI;
    private final PurchaseIMEITableModel purIMEITableModel = new PurchaseIMEITableModel();
    private final PurchaseIMEIDetailTableModel detailTableModel = new PurchaseIMEIDetailTableModel();
    
    /**
     * Creates new form PurchaseIMEIEntryDialog
     * @param listDetail
     * @param listIMEI
     */
    public PurchaseIMEIEntryDialog(List<PurDetailHis> listDetail, List<PurchaseIMEINo> listIMEI) {
        super(Util1.getParent(), true);
        initComponents();
        this.listIMEI = listIMEI;
        purIMEITableModel.setListDetail(listDetail);
        detailTableModel.setListIMEINo(listIMEI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchaseDetail = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIMEINo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPurchaseDetail.setModel(purIMEITableModel);
        jScrollPane1.setViewportView(tblPurchaseDetail);

        tblIMEINo.setModel(detailTableModel);
        jScrollPane2.setViewportView(tblIMEINo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblIMEINo;
    private javax.swing.JTable tblPurchaseDetail;
    // End of variables declaration//GEN-END:variables
}
