/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.ui.common.ReportChooseTableModel;
import com.cv.app.util.Util1;

/**
 *
 * @author winswe
 */
public class ReportChooseDialog extends javax.swing.JDialog {

    private final ReportChooseTableModel model = new ReportChooseTableModel();
    private String rName = "SHIFA";
    
    /**
     * Creates new form ReportChooseDialog
     */
    public ReportChooseDialog() {
        super(Util1.getParent(), true);
        initComponents();
    }

    private void initTable(){
        
    }

    public String getrName() {
        return rName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblRList.setModel(model);
        tblRList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRListMouseClicked
        if(evt.getClickCount() == 2){
            int row = tblRList.getSelectedRow();
            rName = model.getReport(row);
            dispose();
        }
    }//GEN-LAST:event_tblRListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRList;
    // End of variables declaration//GEN-END:variables
}
