/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cv.app.pharmacy.ui.util;

import com.cv.app.pharmacy.database.entity.SaleDetailHis;
import com.cv.app.pharmacy.database.entity.SaleWarranty;
import com.cv.app.pharmacy.ui.common.WarrantyTableModel;
import com.cv.app.ui.common.TableDateFieldRenderer;
import com.cv.app.util.Util1;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author winswe
 */
public class SaleWarrantyDialog extends javax.swing.JDialog {

    private WarrantyTableModel tableModel;
    /**
     * Creates new form SaleWarrantyDialog
     */
    public SaleWarrantyDialog(List<SaleDetailHis> listSaleDetail, 
            List<SaleWarranty> listWarranty, String saleInvId) {
        super(Util1.getParent(), true);
        initComponents();
        txtSaleInvId.setText(saleInvId);
        tableModel = new WarrantyTableModel(listSaleDetail);
        tableModel.setListWarranty(listWarranty);
        tblWarranty.setModel(tableModel);
        initTable();
        actionMapping();
        
        Dimension screen = Util1.getScreenSize();
        int x = (screen.width - this.getWidth()) / 2;
        int y = (screen.height - this.getHeight()) / 2;

        setLocation(x, y);
        setVisible(true);
    }

    public List<SaleWarranty> getWarranty(){
        return tableModel.getListWarranty();
    }
    
    private void initTable(){
        tblWarranty.getColumnModel().getColumn(0).setPreferredWidth(10); //Item Code
        tblWarranty.getColumnModel().getColumn(1).setPreferredWidth(150); //Item Description
        tblWarranty.getColumnModel().getColumn(2).setPreferredWidth(30); //Serial
        tblWarranty.getColumnModel().getColumn(3).setPreferredWidth(15); //Warranty
        tblWarranty.getColumnModel().getColumn(4).setPreferredWidth(10); //Start Date
        tblWarranty.getColumnModel().getColumn(5).setPreferredWidth(10); //End Date

        tblWarranty.getColumnModel().getColumn(4).setCellRenderer(new TableDateFieldRenderer());
        tblWarranty.getColumnModel().getColumn(5).setCellRenderer(new TableDateFieldRenderer());
    }
    
    private void actionMapping(){
        tblWarranty.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        tblWarranty.getActionMap().put("ESCAPE", actionClose);
        
        getRootPane().getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", actionClose);
    }
    
    private Action actionClose = new AbstractAction(){
        @Override
        public void actionPerformed(ActionEvent e){ 
            dispose();
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSaleInvId = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarranty = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sale Warranty Entry");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("Sale Vou : ");

        txtSaleInvId.setEditable(false);

        tblWarranty.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblWarranty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblWarranty.setRowHeight(23);
        jScrollPane1.setViewportView(tblWarranty);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSaleInvId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaleInvId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            dispose();
        }
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWarranty;
    private javax.swing.JFormattedTextField txtSaleInvId;
    // End of variables declaration//GEN-END:variables
}
