/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv.app.opd.ui.entry;

import com.cv.app.common.Global;
import com.cv.app.opd.database.entity.Patient;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.DateUtil;
import com.cv.app.util.Util1;
import com.cv.app.util.ZPLUtil;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author cv-svr
 */
public class ZPLPrint extends javax.swing.JPanel {

    private final AbstractDataAccess dao = Global.dao;
    static Logger log = Logger.getLogger(ZPLPrint.class.getName());

    /**
     * Creates new form ZPLPrint
     */
    public ZPLPrint() {
        initComponents();
        initPrinter();
        initCommandText();
    }

    private void initCommandText() {
        txtRegZPLCode.setText("^XA\n"
                + "\n"
                + "^FX Info Section\n"
                + "^CF0,20\n"
                + "^FO10,10^FD       Name : ^FS\n"
                + "^FO115,10^FDPatient#1^FS\n"
                + "^FO10,40^FD         DOB : ^FS\n"
                + "^FO115,40^FD10/07/1999^FS\n"
                + "^FO10,70^FD    Address : ^FS\n"
                + "^FO115,70^FDYangon^FS\n"
                + "^FO9,100^FD Phone No. : ^FS\n"
                + "^FO115,100^FD09979658665^FS\n"
                + "\n"
                + "^FX Bar Code Section\n"
                + "^BY4,2,100\n"
                + "^FO10,140^BC^FD12345678^FS\n"
                + "\n"
                + "^XZ");
    }

    private void initPrinter() {
        List<String> listPrinter = ZPLUtil.getPrinter();
        BindingUtil.BindCombo(cboPrinter, listPrinter);
    }

    private void getPatient() {
        if (txtRegNo.getText() != null && !txtRegNo.getText().trim().isEmpty()) {
            try {
                Patient pt;

                dao.open();
                pt = (Patient) dao.find(Patient.class, txtRegNo.getText().trim());
                dao.close();

                if (pt == null) {
                    txtRegNo.setText(null);
                    txtDOB.setText(null);
                    txtAge.setText(null);
                    txtPtName.setText(null);
                    txtAddress.setText(null);
                    txtPhone.setText(null);

                    JOptionPane.showMessageDialog(Util1.getParent(),
                            "Invalid patient code.",
                            "Patient Code", JOptionPane.ERROR_MESSAGE);
                } else {
                    txtRegNo.setText(pt.getRegNo());
                    txtDOB.setText(DateUtil.toDateStr(pt.getDob()));
                    txtAge.setText(DateUtil.getAge(txtDOB.getText()));
                    txtPtName.setText(pt.getPatientName());
                    txtAddress.setText(pt.getAddress());
                    txtPhone.setText(pt.getContactNo());
                }
            } catch (Exception ex) {
                log.error("getPatient : " + ex.getStackTrace()[0].getLineNumber() + " - " + ex.toString());
            }
        } else {
            txtRegNo.setText(null);
            txtDOB.setText(null);
            txtAge.setText(null);
            txtPtName.setText(null);
            txtAddress.setText(null);
            txtPhone.setText(null);
        }
    }

    private void regClear() {
        txtRegNo.setText(null);
        txtDOB.setText(null);
        txtAge.setText(null);
        txtPtName.setText(null);
        txtAddress.setText(null);
        txtPhone.setText(null);
    }

    private void regPrint() {
        if (txtRegZPLCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(Util1.getParent(), "You need to configure command text.",
                    "Command Text Blank", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtRegNo.getText().trim().isEmpty() || txtPtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(Util1.getParent(), "Invalid patient info.",
                    "Invalid Patient", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String selPrinter = cboPrinter.getSelectedItem().toString();
        try {
            String width = "80 mm";
            String height = "40 mm";
            ZPLUtil.printZpl(txtRegZPLCode.getText().trim(), selPrinter, width, height);
        } catch (Exception ex) {
            log.error("regPrint : selPrinter : " + selPrinter + " " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReg = new javax.swing.JPanel();
        txtRegNo = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        butRegPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRegZPLCode = new javax.swing.JTextArea();
        butRegClear = new javax.swing.JButton();
        cboPrinter = new javax.swing.JComboBox<>();
        panelOPD = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOPDService = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOPDZPLCode = new javax.swing.JTextArea();
        butOPDPrint = new javax.swing.JButton();
        txtOPDClear = new javax.swing.JButton();
        panelOT = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOTService = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOTZPLCode = new javax.swing.JTextArea();
        butOTPrint = new javax.swing.JButton();
        txtOTClear = new javax.swing.JButton();
        panelPharmacy = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPharmacy = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPharZPLCode = new javax.swing.JTextArea();
        butPharPrint = new javax.swing.JButton();
        butPharClear = new javax.swing.JButton();
        panelDC = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbpIPD = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtIPDZPLCode = new javax.swing.JTextArea();
        butIPDPrint = new javax.swing.JButton();
        butIPDClear = new javax.swing.JButton();

        panelReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Register Label Print"));

        txtRegNo.setBorder(javax.swing.BorderFactory.createTitledBorder("Reg No."));
        txtRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNoActionPerformed(evt);
            }
        });

        txtDOB.setEditable(false);
        txtDOB.setBorder(javax.swing.BorderFactory.createTitledBorder("DOB"));

        txtAge.setEditable(false);
        txtAge.setBorder(javax.swing.BorderFactory.createTitledBorder("Age"));

        txtPtName.setEditable(false);
        txtPtName.setFont(Global.textFont);
        txtPtName.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        txtAddress.setEditable(false);
        txtAddress.setFont(Global.textFont);
        txtAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        txtPhone.setEditable(false);
        txtPhone.setFont(Global.textFont);
        txtPhone.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone"));

        butRegPrint.setText("Print");
        butRegPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegPrintActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Command Text"));

        txtRegZPLCode.setColumns(20);
        txtRegZPLCode.setRows(5);
        txtRegZPLCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtRegZPLCode);

        butRegClear.setText("Clear");
        butRegClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegLayout = new javax.swing.GroupLayout(panelReg);
        panelReg.setLayout(panelRegLayout);
        panelRegLayout.setHorizontalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtName)
                    .addComponent(txtAddress)
                    .addGroup(panelRegLayout.createSequentialGroup()
                        .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRegLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butRegPrint)
                            .addComponent(butRegClear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(txtPhone))
                .addContainerGap())
        );
        panelRegLayout.setVerticalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRegNo)
                    .addComponent(txtDOB)
                    .addComponent(txtAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegLayout.createSequentialGroup()
                        .addComponent(butRegPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRegClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRegLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPtName, txtRegNo});

        cboPrinter.setBorder(javax.swing.BorderFactory.createTitledBorder("Printer"));

        panelOPD.setBorder(javax.swing.BorderFactory.createTitledBorder("OPD Service Label Print"));

        tblOPDService.setFont(Global.textFont);
        tblOPDService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOPDService);

        txtOPDZPLCode.setColumns(20);
        txtOPDZPLCode.setRows(5);
        jScrollPane3.setViewportView(txtOPDZPLCode);

        butOPDPrint.setText("Print");

        txtOPDClear.setText("Clear");

        javax.swing.GroupLayout panelOPDLayout = new javax.swing.GroupLayout(panelOPD);
        panelOPD.setLayout(panelOPDLayout);
        panelOPDLayout.setHorizontalGroup(
            panelOPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOPDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOPDLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(panelOPDLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butOPDPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOPDClear, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelOPDLayout.setVerticalGroup(
            panelOPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOPDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOPDLayout.createSequentialGroup()
                        .addComponent(butOPDPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOPDClear)))
                .addContainerGap())
        );

        panelOT.setBorder(javax.swing.BorderFactory.createTitledBorder("OT Service Label Print"));

        tblOTService.setFont(Global.textFont);
        tblOTService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblOTService);

        txtOTZPLCode.setColumns(20);
        txtOTZPLCode.setRows(5);
        jScrollPane5.setViewportView(txtOTZPLCode);

        butOTPrint.setText("Print");

        txtOTClear.setText("Clear");

        javax.swing.GroupLayout panelOTLayout = new javax.swing.GroupLayout(panelOT);
        panelOT.setLayout(panelOTLayout);
        panelOTLayout.setHorizontalGroup(
            panelOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOTLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(panelOTLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butOTPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOTClear, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelOTLayout.setVerticalGroup(
            panelOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOTLayout.createSequentialGroup()
                        .addComponent(butOTPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOTClear)))
                .addContainerGap())
        );

        panelPharmacy.setBorder(javax.swing.BorderFactory.createTitledBorder("Pharmacy Label Print"));

        tblPharmacy.setFont(Global.textFont);
        tblPharmacy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblPharmacy);

        txtPharZPLCode.setColumns(20);
        txtPharZPLCode.setRows(5);
        jScrollPane7.setViewportView(txtPharZPLCode);

        butPharPrint.setText("Print");

        butPharClear.setText("Clear");

        javax.swing.GroupLayout panelPharmacyLayout = new javax.swing.GroupLayout(panelPharmacy);
        panelPharmacy.setLayout(panelPharmacyLayout);
        panelPharmacyLayout.setHorizontalGroup(
            panelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPharmacyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addGroup(panelPharmacyLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butPharPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butPharClear, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelPharmacyLayout.setVerticalGroup(
            panelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPharmacyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPharmacyLayout.createSequentialGroup()
                        .addComponent(butPharPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butPharClear)))
                .addGap(9, 9, 9))
        );

        panelDC.setBorder(javax.swing.BorderFactory.createTitledBorder("IPD Service Label Print"));

        tbpIPD.setFont(Global.textFont);
        tbpIPD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbpIPD);

        txtIPDZPLCode.setColumns(20);
        txtIPDZPLCode.setRows(5);
        jScrollPane9.setViewportView(txtIPDZPLCode);

        butIPDPrint.setText("Print");

        butIPDClear.setText("Clear");

        javax.swing.GroupLayout panelDCLayout = new javax.swing.GroupLayout(panelDC);
        panelDC.setLayout(panelDCLayout);
        panelDCLayout.setHorizontalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butIPDPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butIPDClear, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelDCLayout.setVerticalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addComponent(butIPDPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butIPDClear)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelOT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelOPD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNoActionPerformed
        getPatient();
    }//GEN-LAST:event_txtRegNoActionPerformed

    private void butRegClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegClearActionPerformed
        regClear();
    }//GEN-LAST:event_butRegClearActionPerformed

    private void butRegPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegPrintActionPerformed
        regPrint();
    }//GEN-LAST:event_butRegPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butIPDClear;
    private javax.swing.JButton butIPDPrint;
    private javax.swing.JButton butOPDPrint;
    private javax.swing.JButton butOTPrint;
    private javax.swing.JButton butPharClear;
    private javax.swing.JButton butPharPrint;
    private javax.swing.JButton butRegClear;
    private javax.swing.JButton butRegPrint;
    private javax.swing.JComboBox<String> cboPrinter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panelDC;
    private javax.swing.JPanel panelOPD;
    private javax.swing.JPanel panelOT;
    private javax.swing.JPanel panelPharmacy;
    private javax.swing.JPanel panelReg;
    private javax.swing.JTable tblOPDService;
    private javax.swing.JTable tblOTService;
    private javax.swing.JTable tblPharmacy;
    private javax.swing.JTable tbpIPD;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextArea txtIPDZPLCode;
    private javax.swing.JButton txtOPDClear;
    private javax.swing.JTextArea txtOPDZPLCode;
    private javax.swing.JButton txtOTClear;
    private javax.swing.JTextArea txtOTZPLCode;
    private javax.swing.JTextArea txtPharZPLCode;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPtName;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextArea txtRegZPLCode;
    // End of variables declaration//GEN-END:variables
}
