/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.AccSetting;
import com.cv.app.pharmacy.ui.common.AccountSetupTableModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class AccountSetup extends javax.swing.JPanel {

    private final static Logger LOG = Logger.getLogger(AccountSetup.class.getName());
    private AccSetting currAccSetting = new AccSetting();
    private final AbstractDataAccess dao = Global.dao;
    private int selectedRow = -1;
    private final AccountSetupTableModel tableModel = new AccountSetupTableModel();

    /**
     * Creates new form AccountSetup
     */
    public AccountSetup() {
        initComponents();
        initTable();
    }

    private void initTable() {
        try {
            tableModel.setListAS(dao.findAllHSQL("select o from AccSetting o order by o.accType"));
        } catch (Exception ex) {
            LOG.error("initTable : " + ex.getMessage());
        } finally {
            dao.close();
        }
        //Define table selection model to single row selection.
        tblAccList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Adding table row selection listener.
        tblAccList.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (tblAccList.getSelectedRow() >= 0) {
                selectedRow = tblAccList.convertRowIndexToModel(
                        tblAccList.getSelectedRow());
            }

            if (selectedRow >= 0) {
                setSetting(tableModel.getSelected(selectedRow));
            }
        });
    }

    private void clear() {
        currAccSetting = new AccSetting();
        selectedRow = -1;
        txtBalanceAcc.setText("");
        txtDept.setText("");
        txtDiscAcc.setText("");
        txtPaidAcc.setText("");
        txtSourceAcc.setText("");
        txtTaxAcc.setText("");
        txtType.setText("");
        txtSrcAccIPD.setText("");
        txtDeptIPD.setText("");
        txtType.setEditable(true);
        txtType.requestFocusInWindow();
    }

    private boolean isValidEntry() {
        boolean status = true;

        if (txtType.getText() == null) {
            status = false;
            JOptionPane.showMessageDialog(this, "Type cannot be blank or null.",
                    "Type null error.", JOptionPane.ERROR_MESSAGE);
        } else if (txtType.getText().trim().isEmpty()) {
            status = false;
            JOptionPane.showMessageDialog(this, "Type cannot be blank or null.",
                    "Type null error.", JOptionPane.ERROR_MESSAGE);
        } else {
            currAccSetting.setAccType(txtType.getText().trim());
            currAccSetting.setBalanceAcc(txtBalanceAcc.getText().trim());
            currAccSetting.setDeptCode(txtDept.getText().trim());
            currAccSetting.setDiscAcc(txtDiscAcc.getText().trim());
            currAccSetting.setPayAcc(txtPaidAcc.getText().trim());
            currAccSetting.setSourceAcc(txtSourceAcc.getText().trim());
            currAccSetting.setTaxAcc(txtTaxAcc.getText().trim());
            currAccSetting.setSourceAccIPD(txtSrcAccIPD.getText().trim());
            currAccSetting.setDeptCodeIPD(txtDeptIPD.getText().trim());
        }

        return status;
    }

    private void setSetting(AccSetting accSetting) {
        this.currAccSetting = accSetting;
        txtBalanceAcc.setText(accSetting.getBalanceAcc());
        txtDept.setText(accSetting.getDeptCode());
        txtDiscAcc.setText(accSetting.getDiscAcc());
        txtPaidAcc.setText(accSetting.getPayAcc());
        txtSourceAcc.setText(accSetting.getSourceAcc());
        txtTaxAcc.setText(accSetting.getTaxAcc());
        txtType.setText(accSetting.getAccType());
        txtSrcAccIPD.setText(accSetting.getSourceAccIPD());
        txtDeptIPD.setText(accSetting.getDeptCodeIPD());
        txtType.setEditable(false);
    }

    private void save() {
        try {
            if (isValidEntry()) {
                dao.save(currAccSetting);
                clear();
                tableModel.setListAS(dao.findAllHSQL("select o from AccSetting o order by o.accType"));
            }
        } catch (Exception ex) {
            LOG.error("save : " + ex.toString());
        } finally {
            dao.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiscAcc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPaidAcc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTaxAcc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDept = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSourceAcc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBalanceAcc = new javax.swing.JTextField();
        butSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSrcAccIPD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDeptIPD = new javax.swing.JTextField();

        tblAccList.setModel(tableModel);
        jScrollPane1.setViewportView(tblAccList);

        jLabel1.setText("Type : ");

        jLabel2.setText("Discount Acc : ");

        jLabel3.setText("Paid Acc : ");

        jLabel4.setText("Tax Acc : ");

        jLabel5.setText("Department : ");

        jLabel6.setText("Source Acc : ");

        jLabel7.setText("Balance Acc : ");

        butSave.setText("Save");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        jLabel8.setText("Src Acc IPD :");

        jLabel9.setText("Dept IPD : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeptIPD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSrcAccIPD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaidAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaxAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSourceAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBalanceAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBalanceAcc, txtDept, txtDiscAcc, txtPaidAcc, txtSourceAcc, txtTaxAcc, txtType});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDiscAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPaidAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTaxAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSourceAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBalanceAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSrcAccIPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDeptIPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butSave)
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        save();
    }//GEN-LAST:event_butSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccList;
    private javax.swing.JTextField txtBalanceAcc;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtDeptIPD;
    private javax.swing.JTextField txtDiscAcc;
    private javax.swing.JTextField txtPaidAcc;
    private javax.swing.JTextField txtSourceAcc;
    private javax.swing.JTextField txtSrcAccIPD;
    private javax.swing.JTextField txtTaxAcc;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
