/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.setup;

import com.cv.app.common.ComBoBoxAutoComplete;
import com.cv.app.common.Global;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.MachineInfo;
import com.cv.app.pharmacy.database.entity.MachineProperty;
import com.cv.app.pharmacy.ui.common.MachinePropTableModel;
import com.cv.app.ui.common.BestTableCellEditor;
import com.cv.app.util.BindingUtil;
import com.cv.app.util.Util1;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class MachinePropSetup extends javax.swing.JPanel {

    static Logger log = Logger.getLogger(MachinePropSetup.class.getName());
    private final AbstractDataAccess dao = Global.dao;
    private MachinePropTableModel tableModel = new MachinePropTableModel(dao);

    /**
     * Creates new form SysPropSetup
     */
    public MachinePropSetup() {
        initComponents();
        setProperties();
        actionMapping();
        initTable();
        initCombo();

        MachineInfo mi = (MachineInfo) cboMachine.getSelectedItem();
        if (mi != null) {
            int machineId = mi.getMachineId();
            tableModel.setMachineId(machineId);
        } else {
            tableModel.setMachineId(-1);
        }
        tableModel.addNewRow();
    }

    private void initCombo() {
        try {
            BindingUtil.BindCombo(cboMachine, dao.findAll("MachineInfo"));
            new ComBoBoxAutoComplete(cboMachine);
        } catch (Exception ex) {
            log.error("initCombo : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private void setProperties() {
        try {
            List<MachineProperty> listProperties = dao.findAll("MachineProperty");
            tableModel.setListMachineProperty(listProperties);
        } catch (Exception ex) {
            log.error("setProperties : " + ex.getMessage());
        } finally {
            dao.close();
        }
    }

    private Action actionItemDelete = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            int yes_no = -1;

            if (tblProperty.getSelectedRow() >= 0) {
                try {
                    yes_no = JOptionPane.showConfirmDialog(Util1.getParent(),
                            "Are you sure to delete?",
                            "Sale item delete", JOptionPane.YES_NO_OPTION);

                    if (tblProperty.getCellEditor() != null) {
                        tblProperty.getCellEditor().stopCellEditing();
                    }
                } catch (Exception ex) {
                    log.error("actionItemDelete : " + ex.getStackTrace()[0].getLineNumber() + " - " + ex.getMessage());
                }
            }

            if (yes_no == 0) {
                int index = tblProperty.convertRowIndexToModel(tblProperty.getSelectedRow());
                tableModel.deleteMachineProperty(index);
            }
        }
    };

    private void actionMapping() {
        //F8 event on tblProperty
        tblProperty.getInputMap().put(KeyStroke.getKeyStroke("F8"), "F8-Action");
        tblProperty.getActionMap().put("F8-Action", actionItemDelete);
    }

    private void initTable() {
        tblProperty.getColumnModel().getColumn(1).setCellEditor(new BestTableCellEditor());
        tblProperty.getColumnModel().getColumn(2).setCellEditor(new BestTableCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperty = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cboMachine = new javax.swing.JComboBox();

        jLabel1.setText("Search Property");

        txtFilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        tblProperty.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblProperty.setModel(tableModel);
        tblProperty.setRowHeight(23);
        jScrollPane1.setViewportView(tblProperty);

        jLabel2.setText("Machine ");

        cboMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMachineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMachineActionPerformed
        MachineInfo mi = (MachineInfo) cboMachine.getSelectedItem();
        if (mi != null) {
            tableModel.setMachineId(mi.getMachineId());
        } else {
            tableModel.setMachineId(-1);
        }
    }//GEN-LAST:event_cboMachineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboMachine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProperty;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
