/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.common.StartWithRowFilter;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.SysProperty;
import com.cv.app.pharmacy.ui.common.SysPropTableModel;
import com.cv.app.ui.common.BestTableCellEditor;
import com.cv.app.util.Util1;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class SysPropSetup extends javax.swing.JPanel {

    static Logger log = Logger.getLogger(SysPropSetup.class.getName());
    private final AbstractDataAccess dao = Global.dao;
    private SysPropTableModel tableModel = new SysPropTableModel(dao);
    private TableRowSorter<TableModel> sorter;
    private StartWithRowFilter swrf;
    
    /**
     * Creates new form SysPropSetup
     */
    public SysPropSetup() {
        initComponents();
        setProperties();
        tableModel.addNewRow();
        actionMapping();
        initTable();

        sorter = new TableRowSorter(tblProperty.getModel());
        tblProperty.setRowSorter(sorter);
        swrf = new StartWithRowFilter(txtFilter);
    }

    private void setProperties() {
        List<SysProperty> listProperties = dao.findAll("SysProperty");
        tableModel.setListSysProperty(listProperties);
    }

    private Action actionItemDelete = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            int yes_no = -1;

            if (tblProperty.getSelectedRow() >= 0) {
                try {
                    yes_no = JOptionPane.showConfirmDialog(Util1.getParent(),
                            "Are you sure to delete?",
                            "Sale item delete", JOptionPane.YES_NO_OPTION);

                    if(tblProperty.getCellEditor() != null){
                        tblProperty.getCellEditor().stopCellEditing();
                    }
                } catch (Exception ex) {
                    //log.info(ex.toString());
                }
            }

            if (yes_no == 0) {
                int index = tblProperty.convertRowIndexToModel(tblProperty.getSelectedRow());
                tableModel.deleteSysProperty(index);
            }
        }
    };

    private void actionMapping() {
        //F8 event on tblProperty
        tblProperty.getInputMap().put(KeyStroke.getKeyStroke("F8"), "F8-Action");
        tblProperty.getActionMap().put("F8-Action", actionItemDelete);
    }

    private void initTable() {
        tblProperty.getColumnModel().getColumn(1).setCellEditor(new BestTableCellEditor());
        tblProperty.getColumnModel().getColumn(2).setCellEditor(new BestTableCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperty = new javax.swing.JTable();

        jLabel1.setText("Search Property");

        txtFilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        tblProperty.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblProperty.setModel(tableModel);
        tblProperty.setRowHeight(23);
        jScrollPane1.setViewportView(tblProperty);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        if (txtFilter.getText().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            if (Util1.getPropValue("system.text.filter.method").equals("SW")) {
                sorter.setRowFilter(swrf);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(txtFilter.getText()));
            }
        }
    }//GEN-LAST:event_txtFilterKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProperty;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
