/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.app.pharmacy.ui.setup;

import com.cv.app.common.Global;
import com.cv.app.pharmacy.database.controller.AbstractDataAccess;
import com.cv.app.pharmacy.database.entity.UserProperty;
import com.cv.app.pharmacy.ui.common.UserPropTableModel;
import com.cv.app.ui.common.BestTableCellEditor;
import com.cv.app.util.Util1;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.apache.log4j.Logger;

/**
 *
 * @author winswe
 */
public class UserPropSetup extends javax.swing.JPanel {

    static Logger log = Logger.getLogger(UserPropSetup.class.getName());
    private final AbstractDataAccess dao = Global.dao;
    private UserPropTableModel tableModel = new UserPropTableModel(dao);

    /**
     * Creates new form SysPropSetup
     */
    public UserPropSetup() {
        initComponents();
        setProperties();
        tableModel.addNewRow();
        actionMapping();
        initTable();
    }

    private void setProperties() {
        List<UserProperty> listProperties = dao.findAll("UserProperty");
        tableModel.setListUserProperty(listProperties);
    }

    private Action actionItemDelete = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            int yes_no = -1;

            if (tblProperty.getSelectedRow() >= 0) {
                try {
                    yes_no = JOptionPane.showConfirmDialog(Util1.getParent(),
                            "Are you sure to delete?",
                            "Sale item delete", JOptionPane.YES_NO_OPTION);

                    if (tblProperty.getCellEditor() != null) {
                        tblProperty.getCellEditor().stopCellEditing();
                    }
                } catch (Exception ex) {
                    //log.info(ex.toString());
                }
            }

            if (yes_no == 0) {
                int index = tblProperty.convertRowIndexToModel(tblProperty.getSelectedRow());
                tableModel.deleteUserProperty(index);
            }
        }
    };

    private void actionMapping() {
        //F8 event on tblProperty
        tblProperty.getInputMap().put(KeyStroke.getKeyStroke("F8"), "F8-Action");
        tblProperty.getActionMap().put("F8-Action", actionItemDelete);
    }

    private void initTable() {
        tblProperty.getColumnModel().getColumn(1).setCellEditor(new BestTableCellEditor());
        tblProperty.getColumnModel().getColumn(2).setCellEditor(new BestTableCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperty = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("Search Property");

        txtFilter.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N

        tblProperty.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        tblProperty.setModel(tableModel);
        tblProperty.setRowHeight(23);
        jScrollPane1.setViewportView(tblProperty);

        jLabel2.setText("User ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProperty;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
